version: '3.7'

services:

  web:
    image: elephantbox/elephantbox:focal-p81n18-202208
    command: run-services nginx,php-fpm
    environment:
      APP_NAME: demo
      APP_ENV: local
      ENTRYPOINT_SCRIPT: /app/demo/.entryscript.sh
      PHP_IDE_CONFIG: serverName=localhost
    working_dir: /app/demo
    ports:
      - 8000:80
    volumes:
      - .:/app
      - /Users/ralphschindler/.composer/auth.json:/root/.composer/auth.json

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
